### ISSUE TITLE
Check for write access not working

### ISSUE THREAD

**Issue by Ian-CMM** [QuiteYellowStudio/InDesign-Feature-Set-Locale-Switcher-macOS#1]
Great script, Jack! I've been using this for several months now but use it infrequently enough that I sometimes forget that I need to have write access for applicationpreference.plist. I can see that the script is trying to check for write access on line 33 but that never seems to work for me. Any thoughts?

macOS 14.6.1 (23G93)
InDesign 19.5

**Comment by QuiteYellow** [comment]
Cheers, Ian

I'll take a look and see if there's a more reliable way to check for write permissions. 

One good way to maintain permanent write permissions for applicationpreference.plist is to install InDesign into `/Users/[username]/Applications/`.

**Comment by QuiteYellow** [comment]
I've added an additonal check, let me know if that resolves the issue, the latest release is here: [Releases](https://github.com/jackweekes/InDesign-Feature-Set-Locale-Switcher-macOS/releases).

**Comment by Ian-CMM** [comment]
Thanks Jack! Seems to work now!

**Comment by QuiteYellow** [comment]
@Ian-CMM, I appear to have got the check the wrong way around in the previous release, I've updated the script and hopefully resloved that issue now.
